version: '3.8'

services:
  db:
    image: postgres:17-alpine
    container_name: django_db_prod
    restart: always
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      - TZ=UTC
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U django_gamehub_user -d django_gamegub_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - django_network_prod

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_backend_prod
    restart: always
    command: sh -c "python manage.py makemigrations --noinput && python manage.py migrate --noinput && daphne Gamehub.asgi:application --bind 0.0.0.0 --port 8000"
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - django_network_prod

volumes:
  postgres_data_prod:

networks:
  django_network_prod:
    driver: bridge